apiVersion: v1
kind: LimitRange
metadata:
  name: lr-1
  namespace: nm-4
spec:
  limits:
    - type: Container
      min:
        memory: 0.1Gi
      max:
        memory: 0.5Gi
      maxLimitRequestRatio:
        memory: 1
      defaultRequest:
        memory: 0.5Gi
      default:
        memory: 0.5Gi
