apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: nm-3
spec:
  containers:
    - name: container
      image: kubetm/app
      resources:
        requests:
          memory: 0.2Gi
        limits:
          memory: 0.4Gi
