apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    type: web
spec:
  containers:
    - name: container
      image: tmkube/app:v1
  # Pod를 삭제시키면, 기본적으로 30초후에 삭제되도록 설정이 되어있는데 0을 세팅하면, 바로 삭제된다.
  terminationGracePeriodSeconds: 0
