apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica1
spec:
  replicas: 1
  selector: # selector에 있는 내용이 template.metadata.labels에 붙어있어야한다.
    matchLabels:
      type: web
      ver: v1
    # matchExpressions 
    # 사전에 어떤 오브젝트가 미리 만들어져 있는 상황에서
    # 그 오브젝트들에 여러 라벨들이 붙어 있고, 내가 원하는 오브젝트만 세밀하게 사용하고 싶을때 사용한다.
    matchExpressions:
      - {key: type, operator: In, values:[web]}
      - {key: ver, operator: Exists}
  template:
    metadata:
      name: pod1
      labels: # selector에 있는 내용이 labels에 붙어있어야한다.
        type: web
        ver: v1
        ver: v2
    spec:
      containers:
        - name: container
          image: tmkube/app:v1
      terminationGracePeriodSeconds: 0