apiVersion: v1
kind: Service
metadata:
  name: service-2
spec:
  selector:
    app: pod
  ports:
    - port: 9000
      targetPort: 8080
      nodePort: 30000 # 모든 노드에 Port가 만들어진다. (30000 ~ 32767)
  type: NodePort
  externalTrafficPolicy: Local
