apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  selector:
    app: pod
  ports:
    - port: 9000 # 9000번 포트로 들어오면
      targetPort: 8080 # 8080번 포트를 가진 Pod에 연결된다.
  # type: ClusterIP Optional이라서 생략을 할 수 있다.
