apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-3
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube
  containers:
    - name: container
      image: kubetm/init
      volumeMounts:
        - name: host-path
          mountPath: /mount1
  volumes:
    - name: host-path
      hostPath:
        path: /node-v # 해당 디렉토리가 미리 만들어져 있어야 에러가 나지 않는다.
        type: DirectoryOrCreate
